version: "3.7"

services:
  n8n:
    container_name: n8n
    build:
      context: ..  # Points to ~/custom-n8n/
      dockerfile: docker/n8n/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=${NODE_FUNCTION_ALLOW_EXTERNAL}
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://${SUBDOMAIN}.${DOMAIN_NAME}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - KIWI_SERVICE_URL=http://kiwi-service:3000
      - WINK_SERVICE_URL=http://wink-service:3001
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"  # Map port for local testing
    networks:
      - nlp-net
    depends_on:
      - kiwi-service
      - wink-service

  kiwi-service:
    container_name: kiwi-service
    build:
      context: ..  # Points to ~/custom-n8n/
      dockerfile: docker/kiwi/Dockerfile
    restart: unless-stopped
    environment:
      - PORT=3000
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    ports:
      - "3000:3000"  # Map port for local testing
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - nlp-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  wink-service:
    container_name: wink-service
    build:
      context: ..  # Points to ~/custom-n8n/
      dockerfile: docker/wink/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    ports:
      - "3001:3001"  # Map port for local testing
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - nlp-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  nginx:
    container_name: n8n-reverse-proxy
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - n8n
      - kiwi-service
      - wink-service
    networks:
      - nlp-net

networks:
  nlp-net:
    driver: bridge

volumes:
  n8n_data:
    external: true
