name: Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KIWI_IMAGE_NAME: ghcr.io/${{ github.repository }}/kiwi-service
  WINK_IMAGE_NAME: ghcr.io/${{ github.repository }}/wink-service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Create log directories
        run: |
          mkdir -p logs
          chmod 777 logs

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker compose -f config/docker-compose.yml build
          docker compose -f config/docker-compose.yml push

      - name: Show built images
        run: docker images 