name: Docker Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/workflows/docker-build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Kiwi service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/kiwi/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/kiwi-service:latest
    
    - name: Build and push Wink service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/wink/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/wink-service:latest 