name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KIWI_SERVICE_URL: http://localhost:3000
  WINK_SERVICE_URL: http://localhost:3001
  NODE_ENV: test
  KIWI_IMAGE_NAME: ghcr.io/${{ github.repository }}/kiwi-service
  WINK_IMAGE_NAME: ghcr.io/${{ github.repository }}/wink-service

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      kiwi-service:
        image: ghcr.io/${{ github.repository }}/kiwi-service:latest
        env:
          NODE_ENV: test
        ports:
          - 3000:3000
        options: >-
          --health-cmd "curl -f http://localhost:3000/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      wink-service:
        image: ghcr.io/${{ github.repository }}/wink-service:latest
        env:
          NODE_ENV: test
        ports:
          - 3001:3001
        options: >-
          --health-cmd "curl -f http://localhost:3001/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './tests/package-lock.json'
      
      - name: Install Dependencies
        working-directory: ./tests
        run: npm ci
      
      - name: Run Integration Tests
        working-directory: ./tests
        run: npm run test:integration
        env:
          KIWI_SERVICE_URL: http://localhost:3000
          WINK_SERVICE_URL: http://localhost:3001
      
      - name: Run Unit Tests
        working-directory: ./tests
        run: npm run test:unit
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/test-results/ 