name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  KIWI_SERVICE_URL: http://localhost:3000
  WINK_SERVICE_URL: http://localhost:3001
  NODE_ENV: test
  KIWI_IMAGE_NAME: ghcr.io/${{ github.repository }}/kiwi-service
  WINK_IMAGE_NAME: ghcr.io/${{ github.repository }}/wink-service

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      kiwi-service:
        image: ghcr.io/${{ github.repository }}/kiwi-service:latest
        env:
          NODE_ENV: test
        ports:
          - 3000:3000
        volumes:
          - ./logs:/app/logs
        options: >-
          --health-cmd "curl -f http://localhost:3000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      wink-service:
        image: ghcr.io/${{ github.repository }}/wink-service:latest
        env:
          NODE_ENV: test
        ports:
          - 3001:3001
        volumes:
          - ./logs:/app/logs
        options: >-
          --health-cmd "curl -f http://localhost:3001/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      # Docker 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Docker Compose 설치 (apt를 통한 설치)
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './tests/package-lock.json'
      
      - name: Create Required Directories
        run: |
          sudo mkdir -p logs
          sudo chmod -R 777 logs
          sudo mkdir -p tests/test-results
          sudo chmod -R 777 tests/test-results

      - name: Install Dependencies
        working-directory: ./tests
        run: npm ci
      
      - name: Wait for services
        run: |
          timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000/health)" != "200" ]]; do sleep 5; done' || exit 1
          timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3001/health)" != "200" ]]; do sleep 5; done' || exit 1
      
      - name: Run Integration Tests
        working-directory: ./tests
        run: |
          npm run test:integration || true
          find . -name "*.xml" -exec cp {} test-results/ \;
        env:
          KIWI_SERVICE_URL: http://localhost:3000
          WINK_SERVICE_URL: http://localhost:3001
      
      - name: Run Unit Tests
        working-directory: ./tests
        run: |
          npm run test:unit || true
          find . -name "*.xml" -exec cp {} test-results/ \;

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/test-results/
            logs/ 